"""Build reports/LAPORAN.md — the authoritative single report covering all CASME II runs.

Modeled after fer.reporting.report:
- Reads results directly from results/results.csv (generated by collect.py)
- Injects narrative prose from docs/narasi.md
- Renders comprehensive master progression table covering ALL runs in clean sequential order
- Outputs a single, structured, authoritative reports/LAPORAN.md without loose appendix dumps
"""
import os
import re
import sys
from datetime import datetime
from typing import Optional

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
SRC = os.path.join(ROOT, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

import pandas as pd

from casme.paths import NARRATIVE_MD, REPORT_MD, REPORTS_DIR, RESULTS_CSV


def num(value, digits=4) -> str:
    """Format floating point numbers with Indonesian decimal comma."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "—"
    try:
        return f"{float(value):.{digits}f}".replace(".", ",")
    except (ValueError, TypeError):
        return str(value)


def narrative(section: str) -> str:
    """Extract a narrative block from docs/narasi.md."""
    if not os.path.exists(NARRATIVE_MD):
        return ""
    with open(NARRATIVE_MD, "r", encoding="utf-8") as f:
        text = f.read()
    match = re.search(rf"<!-- bagian: {section} -->(.*?)<!-- /bagian -->", text, re.S)
    return match.group(1).strip() if match else ""


import glob

def build_run_artifacts_link(run_name: str, root_dir: str) -> str:
    """Build compact markdown links to visual artifacts, configs, and logs for a given run."""
    run_dir = os.path.join(root_dir, "runs", run_name)
    if not os.path.exists(run_dir):
        return "—"

    links = []
    # 1. Config
    prefix = run_name.split("_")[0]
    cfg_candidates = glob.glob(os.path.join(root_dir, "configs", f"{prefix}_*.json"))
    if cfg_candidates:
        cfg_name = os.path.basename(cfg_candidates[0])
        links.append(f"[Config](../configs/{cfg_name})")
    elif os.path.exists(os.path.join(run_dir, "config.json")):
        links.append(f"[Config](../runs/{run_name}/config.json)")

    # 2. Visuals & Logs
    if os.path.exists(os.path.join(run_dir, "confusion_matrix.png")):
        links.append(f"[CM](../runs/{run_name}/confusion_matrix.png)")
    if os.path.exists(os.path.join(run_dir, "roc_curve.png")):
        links.append(f"[ROC](../runs/{run_name}/roc_curve.png)")
    if os.path.exists(os.path.join(run_dir, "curve_training.png")):
        links.append(f"[Curves](../runs/{run_name}/curve_training.png)")
    if os.path.exists(os.path.join(run_dir, "per_fold.csv")):
        links.append(f"[Folds](../runs/{run_name}/per_fold.csv)")
    elif os.path.exists(os.path.join(run_dir, "predictions.csv")):
        links.append(f"[Preds](../runs/{run_name}/predictions.csv)")
    if os.path.exists(os.path.join(run_dir, "run.log")):
        links.append(f"[Log](../runs/{run_name}/run.log)")

    return " • ".join(links) if links else f"[Folder](../runs/{run_name})"


def generate_report(verbose: bool = True) -> str:
    """Generate reports/LAPORAN.md from results.csv and narrative blocks."""
    os.makedirs(REPORTS_DIR, exist_ok=True)

    if not os.path.exists(RESULTS_CSV):
        from casme.reporting.collect import collect
        df = collect(verbose=False)
    else:
        df = pd.read_csv(RESULTS_CSV)

    now_str = datetime.now().strftime("%d %B %Y, %H:%M")

    lines = [
        "# Laporan Eksperimen CASME II — Klasifikasi Micro-Expression (5 Kelas)",
        "",
        f"Dibuat otomatis dari hasil eksperimen pada **{now_str}**.",
        "Regenerasi laporan: `python -m casme.reporting.report` atau `bash scripts/rebuild_reports.sh`.",
        "",
        "Seluruh data angka terpusat di `results/results.csv` (satu baris per run). Dokumen ini adalah satu-satunya file laporan resmi proyek; narasi disunting di `docs/narasi.md`.",
        "",
        "---",
        "",
        "## 1. Pengantar & Arsitektur Model",
        "",
        narrative("pengantar"),
        "",
        narrative("peringatan_jendela"),
        "",
        "### Spesifikasi Arsitektur & Pipeline",
        "",
        narrative("arsitektur"),
        "",
        "---",
        "",
        "## 2. Protokol Pengujian & Evaluasi",
        "",
        narrative("protokol"),
        "",
        "---",
        "",
        "## 3. Ringkasan Model Acuan vs Champion",
        "",
        "| Kategori Model | Run ID | Protokol / Split | UF1 | UAR | ACC | Status Evaluasi | Detail & Artefak | Catatan Implementasi |",
        "|---|---|---|---|---|---|---|---|---|",
        f"| **R3D-18 Baseline** | [`061_r3d_v2_dev_p5`](../runs/061_r3d_v2_dev_p5) | Grouped 4-fold | 0,6816 | 0,7120 | 0,6823 | Acuan Dev | {build_run_artifacts_link('061_r3d_v2_dev_p5', ROOT)} | TV-L1 onset-referenced flow, 128x128 |",
        f"| **Champion Oracle** | [`068_fusion_baseline_iter43_50full_50apex`](../runs/068_fusion_baseline_iter43_50full_50apex) | Grouped 4-fold | 0,7104 | 0,7345 | 0,7083 | Oracle Ref | {build_run_artifacts_link('068_fusion_baseline_iter43_50full_50apex', ROOT)} | Fusi 50:50 full + apex beranotasi dataset |",
        f"| **Champion Deployable** | [`096_fusion_deployable_50full_50auto47`](../runs/096_fusion_deployable_50full_50auto47) | Grouped 4-fold | **0,7021** | **0,7418** | **0,6979** | **CHAMPION APP** | {build_run_artifacts_link('096_fusion_deployable_50full_50auto47', ROOT)} | Fusi 50:50 full + auto-apex (label-free) |",
        f"| **Baseline R3D-18 (LOSO 26)** | [`017_r3d`](../runs/017_r3d) | LOSO 26 | 0,7145 | 0,7207 | 0,6870 | Benchmark | {build_run_artifacts_link('017_r3d', ROOT)} | Evaluasi 26 subjek literatur |",
        f"| **Region Attention s42** | [`163_r3d_regionattn_full_s42_v2_dev_loso_dev_p5`](../runs/163_r3d_regionattn_full_s42_v2_dev_loso_dev_p5) | LOSO 21 | 0,7283 | 0,7350 | 0,7188 | Lolos Gate | {build_run_artifacts_link('163_r3d_regionattn_full_s42_v2_dev_loso_dev_p5', ROOT)} | Segmentasi wajah statis (P=80,1%) |",
        f"| **Champion R3D-18 AU (LOSO 26)** | [`188_r3d_au05_full_s42_v2_dev_loso_all_p5`](../runs/188_r3d_au05_full_s42_v2_dev_loso_all_p5) | LOSO 26 | **0,7211** | **0,7378** | **0,6992** | **CHAMPION UTAMA** | {build_run_artifacts_link('188_r3d_au05_full_s42_v2_dev_loso_all_p5', ROOT)} | R3D-18 + 11-AU Multi-Task ($\\lambda=0.5$) |",
        "",
        "---",
        "",
        "## 4. Semua Run Sekilas (Master Progression Table)",
        "",
        "> [!IMPORTANT]",
        "> **Alur Narasi & Master Progression Table Terkurasi untuk Paper:**",
        "> Untuk keperluan penulisan artikel ilmiah (*research paper*), telah dikurasi alur narasi 6 babak dengan 22 run kunci yang dilengkapi analisis mendalam pada dokumen:",
        "> 👉 **[CASME II Experimental Progression & Research Narrative](../docs/paper_progression_narrative.md)**",
        "",
        f"Daftar lengkap seluruh **{len(df)} run** eksperimen yang tercatat di `runs/` dan `results/results.csv`, diurutkan secara numerik dari `000_` s.d. selesai:",
        "",
        "| Run | Protokol | Split | Backbone | UF1 | UAR | ACC | Epochs | Waktu Selesai | Tautan Detail & Artefak |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]

    # Populate all runs in master table
    for _, r in df.iterrows():
        raw_name = str(r.get("run", ""))
        run_link = f"[`{raw_name}`](../runs/{raw_name})" if os.path.exists(os.path.join(ROOT, "runs", raw_name)) else f"`{raw_name}`"
        proto = str(r.get("protocol", "—"))
        split = str(r.get("split", "—"))
        bb = str(r.get("backbone", "—"))
        if bb == "" or pd.isna(bb):
            bb = "—"
        uf1 = num(r.get("UF1"))
        uar = num(r.get("UAR"))
        acc = num(r.get("ACC"))
        ep = str(r.get("epochs", "—"))
        if ep != "—" and not pd.isna(r.get("epochs")):
            try:
                ep = str(int(float(ep)))
            except Exception:
                pass
        else:
            ep = "—"
        t = str(r.get("time", "—"))[:10]
        if t == "—" or t == "nan":
            t = "tersimpan"
        art_links = build_run_artifacts_link(raw_name, ROOT)
        lines.append(f"| {run_link} | {proto} | {split} | {bb} | {uf1} | {uar} | {acc} | {ep} | {t} | {art_links} |")

    lines.extend([
        "",
        "---",
        "",
        "## 5. Temuan Utama & Analisis Empiris",
        "",
        narrative("temuan_utama"),
        "",
        "---",
        "",
        "## 6. Cabang yang Ditutup (Pelajaran Negatif & Dead-Ends)",
        "",
        narrative("cabang_ditutup"),
        "",
        "---",
        "",
        f"## 7. Statistik Repositori & Prosedur Reproduksi",
        "",
        f"- **Total Run Tercatat:** {len(df)} eksperimen mandiri (tersimpan di `runs/` dan terindeks di `results/results.csv`).",
        "- **Struktur Repositori:** Bersih dan terstandarisasi penuh (`configs/NNN_*.json`, `runs/NNN_*/`, `results/results.csv`, `reports/LAPORAN.md`).",
        "- **Pemeriksaan Integritas:** Jalankan `bash scripts/check.sh` untuk memverifikasi struktur dan unittests.",
        "- **Regenerasi Hasil & Laporan:** Jalankan `bash scripts/rebuild_reports.sh` untuk menyusun ulang tabel dan laporan secara deterministik tanpa training ulang.",
        ""
    ])

    report_content = "\n".join(lines)
    with open(REPORT_MD, "w", encoding="utf-8") as f:
        f.write(report_content)

    if verbose:
        print(f"Generated master report at {REPORT_MD} ({len(lines)} lines, {len(df)} runs).")
    return report_content


if __name__ == "__main__":
    generate_report(verbose=True)
