"""Build reports/LAPORAN.md — the authoritative single report covering all CASME II runs.

Modeled after fer.reporting.report:
- Reads results directly from results/results.csv (generated by collect.py)
- Injects narrative prose from docs/narasi.md
- Renders comprehensive master progression table covering ALL runs in clean sequential order
- Outputs a single, structured, authoritative reports/LAPORAN.md without loose appendix dumps
"""
import os
import re
import sys
from datetime import datetime
from typing import Optional

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
SRC = os.path.join(ROOT, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

import pandas as pd

from casme.paths import NARRATIVE_MD, REPORT_MD, REPORTS_DIR, RESULTS_CSV


def num(value, digits=4) -> str:
    """Format floating point numbers with Indonesian decimal comma."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "—"
    try:
        return f"{float(value):.{digits}f}".replace(".", ",")
    except (ValueError, TypeError):
        return str(value)


def narrative(section: str) -> str:
    """Extract a narrative block from docs/narasi.md."""
    if not os.path.exists(NARRATIVE_MD):
        return ""
    with open(NARRATIVE_MD, "r", encoding="utf-8") as f:
        text = f.read()
    match = re.search(rf"<!-- bagian: {section} -->(.*?)<!-- /bagian -->", text, re.S)
    return match.group(1).strip() if match else ""


def generate_report(verbose: bool = True) -> str:
    """Generate reports/LAPORAN.md from results.csv and narrative blocks."""
    os.makedirs(REPORTS_DIR, exist_ok=True)

    if not os.path.exists(RESULTS_CSV):
        from casme.reporting.collect import collect
        df = collect(verbose=False)
    else:
        df = pd.read_csv(RESULTS_CSV)

    now_str = datetime.now().strftime("%d %B %Y, %H:%M")

    lines = [
        "# Laporan Eksperimen CASME II — Klasifikasi Micro-Expression (5 Kelas)",
        "",
        f"Dibuat otomatis dari hasil eksperimen pada **{now_str}**.",
        "Regenerasi laporan: `python -m casme.reporting.report` atau `bash scripts/rebuild_reports.sh`.",
        "",
        "Seluruh data angka terpusat di `results/results.csv` (satu baris per run). Dokumen ini adalah satu-satunya file laporan resmi proyek; narasi disunting di `docs/narasi.md`.",
        "",
        "---",
        "",
        "## 1. Pengantar & Arsitektur Model",
        "",
        narrative("pengantar"),
        "",
        narrative("peringatan_jendela"),
        "",
        "### Spesifikasi Arsitektur & Pipeline",
        "",
        narrative("arsitektur"),
        "",
        "---",
        "",
        "## 2. Protokol Pengujian & Evaluasi",
        "",
        narrative("protokol"),
        "",
        "---",
        "",
        "## 3. Ringkasan Model Acuan vs Champion",
        "",
        "| Kategori Model | Run ID | Protokol / Split | UF1 | UAR | ACC | Status Evaluasi | Catatan Implementasi |",
        "|---|---|---|---|---|---|---|---|",
        "| **R3D-18 Baseline** | `061_r3d_v2_dev_p5` | Grouped 4-fold | 0,6816 | 0,7120 | 0,6823 | Acuan Dev | TV-L1 onset-referenced flow, 128x128 |",
        "| **Champion Oracle** | `068_fusion_baseline_iter43_50full_50apex` | Grouped 4-fold | 0,7104 | 0,7345 | 0,7083 | Oracle Ref | Fusi 50:50 full + apex beranotasi dataset |",
        "| **Champion Deployable** | `096_fusion_deployable_50full_50auto47` | Grouped 4-fold | **0,7021** | **0,7418** | **0,6979** | **CHAMPION APP** | Fusi 50:50 full + auto-apex (label-free) |",
        "| **Baseline R3D-18 (LOSO 26)** | `017_r3d` | LOSO 26 | 0,7145 | 0,7207 | 0,6870 | Benchmark | Evaluasi 26 subjek literatur |",
        "| **Region Attention s42** | `163_r3d_regionattn_full_s42_v2_dev_loso_dev_p5` | LOSO 21 | 0,7283 | 0,7350 | 0,7188 | Lolos Gate | Segmentasi wajah statis (P=80,1%) |",
        "",
        "---",
        "",
        "## 4. Semua Run Sekilas (Master Progression Table)",
        "",
        f"Daftar lengkap seluruh **{len(df)} run** eksperimen yang tercatat di `runs/` dan `results/results.csv`, diurutkan secara numerik dari `000_` s.d. selesai:",
        "",
        "| Run | Protokol | Split | Backbone | UF1 | UAR | ACC | Epochs | Waktu Selesai |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    # Populate all runs in master table
    for _, r in df.iterrows():
        r_name = f"`{r.get('run', '')}`"
        proto = str(r.get("protocol", "—"))
        split = str(r.get("split", "—"))
        bb = str(r.get("backbone", "—"))
        if bb == "" or pd.isna(bb):
            bb = "—"
        uf1 = num(r.get("UF1"))
        uar = num(r.get("UAR"))
        acc = num(r.get("ACC"))
        ep = str(r.get("epochs", "—"))
        if ep != "—" and not pd.isna(r.get("epochs")):
            try:
                ep = str(int(float(ep)))
            except Exception:
                pass
        else:
            ep = "—"
        t = str(r.get("time", "—"))[:10]
        if t == "—" or t == "nan":
            t = "tersimpan"
        lines.append(f"| {r_name} | {proto} | {split} | {bb} | {uf1} | {uar} | {acc} | {ep} | {t} |")

    lines.extend([
        "",
        "---",
        "",
        "## 5. Temuan Utama & Analisis Empiris",
        "",
        narrative("temuan_utama"),
        "",
        "---",
        "",
        "## 6. Cabang yang Ditutup (Pelajaran Negatif & Dead-Ends)",
        "",
        narrative("cabang_ditutup"),
        "",
        "---",
        "",
        f"## 7. Statistik Repositori & Prosedur Reproduksi",
        "",
        f"- **Total Run Tercatat:** {len(df)} eksperimen mandiri (tersimpan di `runs/` dan terindeks di `results/results.csv`).",
        "- **Struktur Repositori:** Bersih dan terstandarisasi penuh (`configs/NNN_*.json`, `runs/NNN_*/`, `results/results.csv`, `reports/LAPORAN.md`).",
        "- **Pemeriksaan Integritas:** Jalankan `bash scripts/check.sh` untuk memverifikasi struktur dan unittests.",
        "- **Regenerasi Hasil & Laporan:** Jalankan `bash scripts/rebuild_reports.sh` untuk menyusun ulang tabel dan laporan secara deterministik tanpa training ulang.",
        ""
    ])

    report_content = "\n".join(lines)
    with open(REPORT_MD, "w", encoding="utf-8") as f:
        f.write(report_content)

    if verbose:
        print(f"Generated master report at {REPORT_MD} ({len(lines)} lines, {len(df)} runs).")
    return report_content


if __name__ == "__main__":
    generate_report(verbose=True)
